---
- name: Prepare and Mount External Storage
  hosts: the_hive
  become: true # Run all tasks with sudo

  tasks:
    - name: Partition the USB drive
      community.general.parted:
        device: /dev/sda
        number: 1
        state: present
        fs_type: ext4
        label: gpt

    - name: Create an ext4 filesystem on the partition
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: Create the mount point directory
      ansible.builtin.file:
        path: /mnt/storage
        state: directory
        mode: '0755'

    - name: Mount the drive and add it to fstab
      ansible.builtin.mount:
        path: /mnt/storage
        src: /dev/sda1
        fstype: ext4
        opts: defaults,nofail
        state: mounted