# n8n-deployment.yaml

# 1. Namespace to keep n8n's resources isolated
apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
# 2. Persistent Volume Claim to store your n8n data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  namespace: n8n
spec:
  # Use the StorageClass provided by your cluster. 'longhorn' is a common choice.
  # If you don't have Longhorn, k3s provides 'local-path'.
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# 3. The main Deployment for the n8n application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:nightly-arm64
          command: ["n8n"]
          args: []
          ports:
            - containerPort: 5678
          env:
            - name: GENERIC_TIMEZONE
              value: "America/Chicago"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data-pvc
---
# 4. A Service to provide a stable network endpoint for n8n
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678