---
- name: Partition the USB drive
  community.general.parted:
    device: "{{ item.device }}"
    number: 1
    state: present
    fs_type: ext4
    label: gpt

- name: Create an ext4 filesystem on the partition
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.partition }}"

- name: Get the UUID of the new partition
  ansible.builtin.command: "blkid -s UUID -o value {{ item.partition }}"
  register: blkid_result
  changed_when: false

- name: Store the partition UUID as a fact
  ansible.builtin.set_fact:
    partition_uuid: "{{ blkid_result.stdout }}"

- name: Create the mount point directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'

- name: Mount the drive by UUID and add it to fstab
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "UUID={{ partition_uuid }}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted