---
- name: Deploy Full Stack via Helm
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure Python dependencies for Kubernetes are installed
      ansible.builtin.pip:
        name: kubernetes-client
        state: present

    # ------------- Helm Repository Setup -------------
    - name: Add the Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
        state: present

    - name: Add the Prefect Helm repository
      kubernetes.core.helm_repository:
        name: prefect
        repo_url: "https://prefecthq.github.io/prefect-helm"
        state: present

    - name: Add the Grafana Helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: "https://grafana.github.io/helm-charts"
        state: present

    - name: Add the Prometheus Community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"
        state: present

    - name: Update all Helm repositories to fetch the latest charts
      ansible.builtin.command: "helm repo update"
      changed_when: false # This command never reports a change

    # ------------- Longhorn Deployment (Storage Layer) -------------
    - name: Deploy or Upgrade the Longhorn chart
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        state: present
        create_namespace: true

    # ------------- Prefect Server Deployment (Application Layer) -------------
    - name: Deploy or Upgrade the Prefect Server chart
      kubernetes.core.helm:
        name: prefect-server
        chart_ref: prefect/prefect-server
        release_namespace: prefect
        state: present
        create_namespace: true
        values:
          # Persistence configuration for the server's database
          database:
            type: "postgresql"
            postgresql:
              postgresqlData:
                persistence:
                  enabled: true
                  storageClassName: "longhorn"
                  size: 5Gi

    # ------------- Prefect Worker Deployment (Execution Layer) -------------
    - name: Deploy or Upgrade the Prefect Worker chart
      kubernetes.core.helm:
        name: prefect-worker
        chart_ref: prefect/prefect-worker
        release_namespace: prefect
        state: present
        create_namespace: true
        values:
          worker:
            # This is the master switch that tells the worker to use a self-hosted server
            apiConfig: "selfHostedServer"
            # General configuration for the worker
            config:
              workPool: "default-agent-pool"
            # API configuration specific to self-hosted mode
            selfHostedServerApiConfig:
              apiUrl: "http://prefect-server.prefect.svc.cluster.local:4200/api"

    # ------------- Prometheus Deployment (Monitoring Backend)
    - name: Deploy or Upgrade the Prometheus Stack chart
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring # Deploys into the same namespace as Grafana
        state: present
        create_namespace: true
        values:
          # Disable Grafana because you are already deploying it separately.
          grafana:
            enabled: false

          # This ensures metrics data survives pod restarts using Longhorn.
          prometheus:
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: "longhorn"
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 20Gi

    # ------------- Grafana Deployment (Monitoring Layer) -------------
    - name: Deploy or Upgrade the Grafana chart
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: monitoring
        state: present
        create_namespace: true
        values:
          # Enable persistence and use Longhorn
          persistence:
            enabled: true
            type: pvc
            storageClassName: "longhorn"
            accessModes:
              - ReadWriteOnce
            size: 5Gi
          adminPassword: "admin"
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  # This is the internal Kubernetes address for the Prometheus service
                  # created by the helm chart we just added.
                  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
                  access: proxy
                  isDefault: true