---
- name: Fetch and Configure Kubeconfig for Local Access
  hosts: the_hive[0] # Run only on the master node
  gather_facts: true

  tasks:
    - name: Fetch k3s.yaml from master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "k3s.yaml" # Saves to a directory named after the host
        flat: true

    - name: Replace localhost with the master's IP address
      ansible.builtin.replace:
        path: "k3s.yaml"
        regexp: '127\.0\.0\.1'
        replace: "{{ ansible_default_ipv4.address }}"
      delegate_to: localhost

    - name: Inform user where to find the file
      ansible.builtin.debug:
        msg: "Your kubeconfig is ready. Move 'k3s.yaml' to '~/.kube/config' to use it."