---
- name: Fetch and Configure Kubeconfig for Local Access
  hosts: the_hive[0] # Targets your first host, the master node
  gather_facts: false

  tasks:
    - name: Read the kubeconfig file from the master node
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      become: yes
      register: k3s_config_slurped

    - name: Save the kubeconfig to your project's root directory
      ansible.builtin.copy:
        # The 'slurp' module base64 encodes content, so we must decode it
        content: "{{ k3s_config_slurped['content'] | b64decode }}"
        dest: "{{ inventory_dir }}/k3s.yaml" # Explicitly save to the project root
        mode: '0600' # Sets secure permissions on the new file
      delegate_to: localhost

    - name: Replace localhost with the master's IP address
      ansible.builtin.replace:
        path: "{{ inventory_dir }}/k3s.yaml" # Use the same explicit path
        regexp: '127\.0\.0\.1'
        # A more reliable way to get the master's IP
        replace: "{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"
      delegate_to: localhost

    - name: Inform user of completion
      ansible.builtin.debug:
        msg: "✅ Kubeconfig is ready at '{{ inventory_dir }}/k3s.yaml'."