---
- name: Prepare and Mount Multiple External Storage Drives
  hosts: the_hive
  become: true # Run all tasks with sudo

  vars_files:
    - storage_vars.yml

  tasks:
    - name: "Partition and format drive {{ item.device }}"
      ansible.builtin.include_tasks: tasks/mount_disk.yml
      loop: "{{ disks_to_mount }}"
      loop_control:
        loop_var: item