---
- name: Prepare Nodes for Longhorn
  hosts: the_hive
  become: true

  tasks:
    - name: Install open-iscsi and nfs-common packages for Longhorn
      ansible.builtin.apt:
        name:
          - open-iscsi
          - nfs-common
        state: present
        update_cache: yes